### ISSUE TITLE
CAA Flights data set review

### ISSUE THREAD

**Issue by canwaf** [GSS-Cogs/ons-faster-economic-indicators#25]
Review the dataset, providing suggestion for changes.

1. Look at the csv
2. Look at the json file
3. Look at the associated concept schemes if they are separate
4. Validate the serialised output folder
5. Provide the feedback as a comment on github

**Comment by abdulkasim1** [comment]
Feedback:
- Include the creator and the date of when the dataset was issued.
- Include the time period of the dataset in the summary. For e.g., from Jan 2019 to Nov 2022.
- Is the theme valid? URI used instead of words.
- Include a label for ‘marker’, ‘Metric’, ‘value’ and ‘Unit’ columns to better describe the columns.
- Include the type of unit the observation is. Use the qudt vocabulary to do this.
- There are no dimensions.
- Describing the label as a 'date' may be wrong since technically yyyy-mm format is not a date. It is using a month template. Therefore, using 'month' would be a more appropriate label.
- Could possibly use a dimension to better describe the dataset. For example, airport name or whether it is an arrival or departure.

**Comment by BenHowland** [comment]
Feedback:

CSV
•	Should metric be the right title for number of passengers.
•	Is count the right unit, should it be number?
•	Should Heathrow be mentioned in any of the columns?

JSON File
•	Can the license and publisher points go above the keywords? Is there a set way of starting the json file?
•	There is no dataset_issued timeframe.
•	We could include from_existing to give more detail to the metadata.
•	We need data_type for value.

**Comment by GregoryJPavier** [comment]
**Feedback**

**JSON**
The classics - No creator or dataset issued, no mentions of the time frame of the dataset
Label given for Date column, but already using ‘from_template’
Also, said table is ‘Date’ but it’s using a month format. If there’s going to be a label it should be ‘Month’
Labels for other columns could be added to better describe what they are
No unit type given for observation

**CSV**
Could perhaps use another column to give more depth to the dataset
Something like the arrival/departure location

**Comment by GregoryJPavier** [comment]
# CAA Flights dataset feedback

## Dataset metadata

- [ ] Creator not provided
- [ ] Date when dataset was issued
- [ ] Time period covered by dataset should be provided in summary

## Columns

- [ ] Don't set column label when using from_template
- [ ] Units should be QUDT's NUM, and assigned at the observation column level, see Example observation and unit columns
below
- [ ] Value column should have a data_type set to "integer"; however the CSV file must change
- [ ] Describing the label as a 'date' may be wrong since technically yyyy-mm format is not a date. It is using a month template. Therefore, using 'month' would be a more appropriate label
- [ ] Add geograhy column with ONS geographical codes to identify the scope of each observation

## CSV section

## Example observation and unit columns

Changes are required to how units are expressed in the qube-config.json, here's an extract of how they would be better represented in the config:

```json
    "columns": {
        ...
        "value": {
            "type": "observation",
            "units": "http://qudt.org/vocab/unit/NUM",
            "data_type": "int"
        },
        "units": false
        ...
    }
```

**Comment by GregoryJPavier** [comment]
Got a quick update. The link for from_existing under the measure needs to be updated.
Instead of: "https://raw.githubusercontent.com/GSS-Cogs/reusable-rdf-resources/main/rdf-definitions/measures/measures.csv#passengers"
It should now be: "https://purl.org/csv-cubed/resources/measures#passengers"

**Comment by harlandc** [comment]
updated the link, thanks @GregoryJPavier  😄
