### ISSUE TITLE
Flights data set review

### ISSUE THREAD

**Issue by canwaf** [GSS-Cogs/ons-faster-economic-indicators#26]
Review the dataset, providing suggestion for changes.

1. Look at the csv
2. Look at the json file
3. Look at the associated concept schemes if they are separate
4. Validate the serialised output folder
5. Provide the feedback as a comment on github

**Comment by abdulkasim1** [comment]
Feedback:
- Include the creator and the date of when the dataset was issued.
- Label may not required for date column as template is being used.
- Include the time period for the dataset in the summary, (e.g., from 2nd Jan 2019 to 6th Dec 2022).
- Is the theme valid? URI used instead of keywords.
- Include a label for ‘marker’, ‘Metric’, ‘value’ and ‘Unit’ columns to better describe the columns. 
- Include the type of unit the observation is. Use the qudt vocabulary to do this.
- Include data type of observations.
- There are no dimensions. Is this an issue? Could include dimensions to describe whether a flight is to, from or within the UK.
- Metric takes two values; number of flights and seven day average. Is a seven day average necessary? Since data is daily if one wants to calculate a seven day average they can simply do this themselves.

**Comment by BenHowland** [comment]
Feedback:

CSV
•	What is the purpose of the marker column?
•	Why is this done on a daily basis but the other flights dataset is monthly?
•	Do we need the decimal point for the value column?
•	Is Count the right unit?
•	Do we need to specify this is for all flights within the UK?

JSON file
•	Can the license and publisher points go above the keywords? Is there a set way of starting the json file?
•	There is no dataset_issued timeframe.
•	We could include from_existing to give more detail to the metadata.
•	We need data_type for value.

**Comment by GregoryJPavier** [comment]
**Feedback**

**JSON**
The classics - No creator or dataset issued, no mentions of the time frame of the dataset
Label given for Date column, but already using ‘from_template’
Labels for other columns could be added to better describe what they are
No unit type given for observation

**CSV**
The Values are decimals. These values should be probably be set as INTs and should reference qudt
Could use a dimension column to better explain where these flights are coming from / going to
The JSON file mentions they’re all to, from, and within the UK, but the dataset itself doesn’t really differentiate between those attributes

**Comment by canwaf** [comment]
# Flights data set review

## Dataset metadata

- [ ] Creator not provided
- [ ] Data when dataset was issued
- [ ] Time period covered by dataset should be provided in summary (e.g. "Number of flights to, from, and within the UK between 1 January 1970 and 19 January 2038")
- [ ] 

## Columns

- [ ] Don't set column label when using from_template
- [ ] Describe measures (e.g. Seven-day average, and number of flights), see https://gss-cogs.github.io/csvcubed-docs/external/guides/configuration/qube-config/#measure-and-unit-columns-configuration
- [ ] Units should be QUDT's NUM, and assigned at the observation column level, see Example observation and unit columns
below
- [ ] Value column should have a data_type set to "integer"; however the CSV file must change

## CSV section
- [ ] values in value column should be integers, without `-.0` suffix

## Example observation and unit columns

Changes are required to how units are expressed in the qube-config.json, here's an extract of how they would be better represented in the config:

```json
    "columns": {
        ...
        "value": {
            "type": "observation",
            "units": "http://qudt.org/vocab/unit/NUM",
            "data_type": "int"
        },
        "units": false
        ...
    }
```

**Comment by harlandc** [comment]
There was a small typo in the issue above- Under "Example observation and unit columns", the "units" key should be "unit", and then it works fine :) Thanks for the help! @bethjwest  will be in touch with a couple questions.
