### ISSUE TITLE
Xero data set review

### ISSUE THREAD

**Issue by canwaf** [GSS-Cogs/ons-faster-economic-indicators#32]
Review the dataset, providing suggestion for changes.

1. Look at the csv
2. Look at the json file
3. Look at the associated concept schemes if they are separate
4. Validate the serialised output folder
5. Provide the feedback as a comment on github

**Comment by GregoryJPavier** [comment]
**Feedback**

**Conifg.json**
- When was the dataset issued? What’s the timeframe?
- Who is the creator?
- Each column would benefit from a measure label to better describe what it represents (aside from month since it’s being taken from a template)
- Include unit types using qudt references

**CSV**
- Nitpick about order of industry types - ‘Other Services’ should be the last entry.
- Makes it confusing to read due to the expectation that it should be last, but ‘Health Care and Social Assistance’ is actually the last entry of each year.
- 100 = avg small business index (for 2019, in this case, but entries from Xero do go back further)
- In the totals section, the totals are ordered sales, jobs, etc, the opposite of the rest of the document where Jobs appears first, then Sales. Would be nice to implement a consistent order.
- How are these totals calculated? Total index is usually a weighed average, I think.

**Comment by BenHowland** [comment]
Feedback:

CSV

•	Is Index right for unit?
•	Will the equal sign affect the processing in the measure column?
•	Do we need total as well as all the other industries. Does the total equal the sub components.
•	With the fact that some of the data has a decimal point and others not. Will this need to be re created throughout the dataset? Or does it not matter to csvcubed. (I think this has been answered in the output file. Sales-and-jobs-at-small-business.csv)
•	Also, some of the numbers go to seven decimal points.

JSON File

•	Can the license and publisher points go above the keywords? Is there a set way of starting the json file?
•	There is no dataset_issued timeframe.
•	We could include from_existing to give more detail to the metadata.
•	Does Industry need its own entry instead of being attached.
•	Do the column headers need to be in the order they are in on the csv?
•	Unit has not been described as Index unlike the csv. (In the xero.csv output the column Unit says unitless.)
•	Does experimental statistics need to be defined anywhere. (That also goes for all the other faster indicators topics). 
•	The title, summary and description do not match the excel spreadsheet from the ONS website. Should small businesses be better defined. I.e., Xero has defined these organisations with fewer than 20 employees.
•	Do we need to incorporate region in this file. Even if it is for United Kingdom.

**Comment by BenHowland** [comment]
# Xero dataset review

## Dataset metadata

-[] Date when datset was issued.
-[] Does experimental statistics need to be defined anywhere. 
(That also goes for all the other faster indicators topics). 
-[] The title, summary and description do not match the excel spreadsheet from 
the ONS website. Should small businesses be better defined. I.e., Xero has 
defined these organisations with fewer than 20 employees.

## Columns

=[] Units should be QUDT's NUM and assigned at the observation column level, see
Example observation and unit columns below.
-[] Each column would benefit from a measure label to better describe what it 
represents.
-[] Do the column headers need to be in the order they are in on the csv?

## CSV section

-[] Values in value column should be integers without '-.0' suffix.
-[] The order of industry types. Should 'Other Services' be the last entry?
-[] The layout for the category column does not follow suit for Total industry. 
Unlike the others.
-[] How are the totals calculated. Are they a weighted average? Do they add up 
correctly from the sub components.
-[] Will the equal sign affect the processing in the measure column?
-[] Do we need to incorporate region in this file. Even if it is for United 
Kingdom.

## Example observation and unit columns

Changes are required to how units are expressed in the qube-config.json, 
here is an extract of how they would be better represented in the config:

    "columns": {
        ...
        "value": {
            "type": "observation",
            "units": "http://qudt.org/vocab/unit/NUM",
            "data_type": "int"
        },
        "units": false
        ...
    }

**Comment by BenHowland** [comment]
#Further Feedback

- [] A recommendation would be to create a second JSON file, to help keep the concept code list separate and allow it to be easily maintained.

This recommendation was for Industry. You could have a separate JSON file for this area. This would enable you to provide more detail for each dimension. With the dimensions being names of the industries. You would be able to apply a label, description, and notation. If you did this, to the original JSON file it would make it unnecessarily long. Also, if you needed to update or add more names to the industries, it would be easier to apply this in a separate JSON file. 
With creating this concept/code list JSON file you would be able to create a parent and child concept. Where Total/All would be the parent and all the other industries would be the children of Total/All.
I have provided the link to show you an example. [Code list](https://gss-cogs.github.io/csvcubed-docs/external/guides/configuration/code-list-config/?h=code+lis)

- [] If you wanted Industry to be sorted in some form of structure. You will manually have to assign priorities to the industries. At the moment it is done automatically.

This was only a suggestion regarding the visual representation of the industries column. If you look at the January 2019 in the csv you have health care and social assistance as the last entry for that month. But you could have other services as the last entry for each month. The way you would do this would be to either manually update the csv or you could create a priority list for the industries. Depending on the layout you wanted. One is already automatically created that you can see for reference in the out folder under industry.csv.
